<?php

namespace MTD\SueldosSalariosBundle\Entity;

/**
 * AntiguedadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AntiguedadRepository extends \Doctrine\ORM\EntityRepository
{
}
