<?php

namespace MTD\SueldosSalariosBundle\Entity;

/**
 * DescuentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DescuentoRepository extends \Doctrine\ORM\EntityRepository
{
}
