<?php

namespace MTD\SueldosSalariosBundle\Entity;

/**
 * Dias_No_TrabajadosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Dias_No_TrabajadosRepository extends \Doctrine\ORM\EntityRepository
{
}
