<?php

namespace MTD\SueldosSalariosBundle\Entity;

/**
 * Falla_AcumuladaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Falla_AcumuladaRepository extends \Doctrine\ORM\EntityRepository
{
}
