<?php

namespace MTD\SueldosSalariosBundle\Entity;

/**
 * MinimoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MinimoRepository extends \Doctrine\ORM\EntityRepository
{
}
