<?php

namespace MTD\SueldosSalariosBundle\Entity;

/**
 * SueldosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SueldosRepository extends \Doctrine\ORM\EntityRepository
{
}
