<?php

namespace MTD\SueldosSalariosBundle\Entity;

/**
 * ViaticoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViaticoRepository extends \Doctrine\ORM\EntityRepository
{
}
