<?php

namespace MTD\ReclutamientoBundle\Entity;

/**
 * EmpleadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpleadoRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByLetters($string){
        return $this->getEntityManager()->createQuery('SELECT u FROM MTDReclutamientoBundle:Empleado u  
                WHERE u.nombre LIKE :string OR u.apellido LIKE :string')
                ->setParameter('string','%'.$string.'%')
                ->getResult();
    }
}
