<?php

namespace MTD\ReclutamientoBundle\Entity;

/**
 * Empleado_RequisitoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Empleado_RequisitoRepository extends \Doctrine\ORM\EntityRepository
{
}
