mtd_categorias_trabajo_homepage:
    path:     /hello/{name}
    defaults: { _controller: MTDCategoriasTrabajoBundle:Default:index }

mtd_categoria_crear:
    path:     /categoria/crear
    defaults: {_controller: MTDCategoriasTrabajoBundle:RegistroCategoria:registro }
    
mtd_requisito_crear:
    path:     /requisito/crear
    defaults: {_controller: MTDCategoriasTrabajoBundle:RegistroRequisito:registro }
    
mtd_requisito_registrar:
    path:     /requisito/registrar
    defaults: {_controller: MTDCategoriasTrabajoBundle:Requisito:registro }
    
mtd_requisito_eliminar:
    path:     /requisito/eliminar/{id}
    defaults: {_controller: MTDCategoriasTrabajoBundle:EliminaRequisito:eliminar }

mtd_categoria_lista:
    path:     /categoria/lista
    defaults: {_controller: MTDCategoriasTrabajoBundle:ListaCategoria:listar }
    
mtd_categoria_editar:
    path:     /categoria/editar/{id}
    defaults: {_controller: MTDCategoriasTrabajoBundle:EditaCategoria:editar }
    
mtd_categoria_eliminar:
    path:     /categoria/eliminar/{id}
    defaults: {_controller: MTDCategoriasTrabajoBundle:EliminaCategoria:eliminar }