mtd_asistencia_homepage:
    path:     /hello/{name}
    defaults: { _controller: MTDAsistenciaBundle:Default:index }
    
mtd_asistencia_empleado:
    path:     /asistencia/postulante/{id}
    defaults: {_controller: MTDAsistenciaBundle:RegistroAsistencia:mostrar }
    
mtd_asistencia_empleado_administrativo:
    path:     /asistencia/administrativo/{id}
    defaults: {_controller: MTDAsistenciaBundle:RegistroAsistenciaAdministrativo:mostrar }

mtd_asistencia_registro:
    path:     /asistencia/registro/{id}
    defaults: {_controller: MTDAsistenciaBundle:RegistroAsistencia:registrar }

mtd_asistencia_registro_administrativo:
    path:     /asistencia/registro/administrativo/{id}
    defaults: {_controller: MTDAsistenciaBundle:RegistroAsistenciaAdministrativo:registrar }
    
mtd_asistencia_operativos:
    path:     /asistencia/operativos
    defaults: {_controller: MTDAsistenciaBundle:ListaOperativos:listar }
    
mtd_asistencia_administrativos:
    path:     /asistencia/administrativos
    defaults: {_controller: MTDAsistenciaBundle:ListaAdministrativos:listar }
    
mtd_asistencia_mostrar:
    path:     /asistencia/empleado/ver/{id}
    defaults: {_controller: MTDAsistenciaBundle:InformacionAsistencia:mostrar }
    
mtd_asistencia_administrativo_mostrar:
    path:     /asistencia/administrativo/ver/{id}
    defaults: {_controller: MTDAsistenciaBundle:InformacionAsistenciaAdministrativo:mostrar }
    
mtd_asistencia_detalle_tabla:
    path:     /asistencia/detalle/tabla/{id}
    defaults: {_controller: MTDAsistenciaBundle:DetalleTabla:mostrar }
    options:
        expose: true
        
mtd_inasistencia_detalle_tabla:
    path:     /inasistencia/detalle/tabla/{id}
    defaults: {_controller: MTDAsistenciaBundle:DetalleTabla:mostrarInasistencia }
    options:
        expose: true
        
mtd_asistencia_elimina:
    path:     /asistencia/elimina/{id}/{idEmpleado}
    defaults: {_controller: MTDAsistenciaBundle:EliminaAsistencia:eliminar }
    
mtd_inasistencia_operativo:
    path:     /inasistencia/operativo/{id}
    defaults: {_controller: MTDAsistenciaBundle:RegistroInasistencia:mostrar }
    
mtd_inasistencia_operativo_registro:
    path:     /inasistencia/operativo/registro/{id}
    defaults: {_controller: MTDAsistenciaBundle:RegistroInasistencia:registrar }
    
mtd_asistencia_feriado:
    path:     /asistencia/feriado
    defaults: {_controller: MTDAsistenciaBundle:RegistroFeriado:registrar }
    
mtd_asistencia_configuracion:
    path:     /asistencia/configuracion
    defaults: {_controller: MTDAsistenciaBundle:RegistroConfiguracion:mostrar }
    
mtd_registrar_configuracion:
    path:     /registrar/configuracion
    defaults: {_controller: MTDAsistenciaBundle:RegistroConfiguracion:registrar }