mtd_proyecto_homepage:
    path:     /hello/{name}
    defaults: { _controller: MTDProyectoBundle:Default:index }

mtd_inicio:
    path:     /inicio
    defaults: {_controller: MTDProyectoBundle:Inicio:mostrar }

mtd_proyecto_registro:
    path:     /proyecto/registro
    defaults: {_controller: MTDProyectoBundle:RegistroProyecto:registro }

mtd_cliente_registro:
    path:     /registro/cliente
    defaults: {_controller: MTDProyectoBundle:RegistroCliente:registroCliente }

mtd_tipoProyecto_registro:
    path:     /registro/tipoProyecto
    defaults: {_controller: MTDProyectoBundle:TipoProyecto:registroTipoProyecto }
    
mtd_lugar_registro:
    path:     /registro/lugar
    defaults: {_controller: MTDProyectoBundle:Lugar:registrar }

mtd_lista_proyecto:
    path:     /proyecto/lista
    defaults: {_controller: MTDProyectoBundle:ListaProyecto:lista }
    
mtd_editar_proyecto:
    path:     /proyecto/editar/{id}
    defaults: {_controller: MTDProyectoBundle:EditaProyecto:editar }
    
mtd_eliminar_proyecto:
    path:     /proyecto/eliminar/{id}
    defaults: {_controller: MTDProyectoBundle:EliminaProyecto:eliminar }
    
mtd_mostrar_proyecto:
    path:     /proyecto/mostrar/{id}
    defaults: {_controller: MTDProyectoBundle:InformacionProyecto:mostrar }
    
mtd_categorias_proyecto:
    path:     /categoria/proyecto/{id}
    defaults: {_controller: MTDProyectoBundle:CategoriaProyecto:listar }
    
mtd_proyecto_empleado:
    path:     /proyecto/empleados/{id}
    defaults: {_controller: MTDProyectoBundle:ProyectoEmpleado:asignar }
    
mtd_proyecto_empleado_nombre:
    path:     /proyecto/empleados/nombre/{id}
    defaults: {_controller: MTDProyectoBundle:ProyectoEmpleadoNombre:mostrar }
    
mtd_proyecto_empleado_agregar:
    path:     /proyecto/empleados/agregar/{id}/{proyecto}
    defaults: {_controller: MTDProyectoBundle:ProyectoEmpleado:mostrar }
    options:
        expose: true
    
mtd_proyecto_empleado_registro:
    path:     /proyecto/empleados/registro/{id}/{idProyecto}
    defaults: {_controller: MTDProyectoBundle:EmpleadoRegistro:registrar }
    
mtd_proyecto_registro_empleado_nombre:
    path:     /proyecto/empleados/nombreRegistro/{idProyecto}
    defaults: {_controller: MTDProyectoBundle:ProyectoEmpleadoNombre:registrar }
    
mtd_proyecto_lista_empleados:
    path:     /proyecto/lista/empleados/{id}
    defaults: {_controller: MTDProyectoBundle:ListaEmpleados:listar }
    
mtd_lista_clientes:
    path:     /clientes/lista
    defaults: {_controller: MTDProyectoBundle:ListaClientes:listar }
    
mtd_cliente_edita:
    path:     /cliente/edita/{id}
    defaults: {_controller: MTDProyectoBundle:EditaCliente:editar }
    
mtd_proyecto_terminado:
    path:     /proyecto/terminado/{id}
    defaults: {_controller: MTDProyectoBundle:ProyectoTerminado:terminar }
    
mtd_lista_proyecto_terminados:
    path:     /proyecto/lista/terminados
    defaults: {_controller: MTDProyectoBundle:ListaProyectoTerminados:listar }