mtd_reclutamiento_homepage:
    path:     /hello/{name}
    defaults: { _controller: MTDReclutamientoBundle:Default:index }

mtd_postulante_registro:
    path:     /postulante/registro
    defaults: {_controller: MTDReclutamientoBundle:RegistroPostulante:registrar }

mtd_lugar_empleado:
    path:     /registro/lugarEmpleado
    defaults: {_controller: MTDReclutamientoBundle:Lugar:registrar }
    
mtd_postulante_requisito:
    path:     /postulante/registroPerfil/{id}
    defaults: {_controller: MTDReclutamientoBundle:FormularioPerfilTecnico:registrar }
        
mtd_postulante_registrar_requisito:
    path:     /postulante/registroRequisitoPerfil/{id}
    defaults: {_controller: MTDReclutamientoBundle:RegistroPerfilTecnico:registrar }
    
mtd_postulante_lista:
    path:     /postulantes/lista
    defaults: {_controller: MTDReclutamientoBundle:Lista:listar }
    
mtd_postulante_ver:
    path:     /postulante/ver/{id}
    defaults: {_controller: MTDReclutamientoBundle:Informacion:mostrar }
    
mtd_postulante_eliminar:
    path:     /postulante/eliminar/{id}
    defaults: {_controller: MTDReclutamientoBundle:EliminaPostulante:eliminar }
    
mtd_postulante_editar:
    path:     /postulante/editar/{id}
    defaults: {_controller: MTDReclutamientoBundle:EditaPostulante:editar }
    
mtd_perfil_tecnico_ver:
    path:     /postulante/perfilTecnico/ver/{id}
    defaults: {_controller: MTDReclutamientoBundle:PerfilTecnicoInformacion:mostrar }
    
mtd_perfil_tecnico_editar:
    path:     /postulante/perfilTecnico/editar/{id}
    defaults: {_controller: MTDReclutamientoBundle:PerfilTecnicoEdita:editar }
    
mtd_postulante_mostrar_requisito_editar:
    path:     /postulante/registroPerfil/requisitos/editar/{id}/{idEmpleado}
    defaults: {_controller: MTDReclutamientoBundle:PerfilTecnicoEdita:mostrarRequisitos }
    options:
        expose: true
        
mtd_buscar_empleado:
    path:     /postulantes/buscar
    defaults: {_controller: MTDReclutamientoBundle:BuscadorEmpleados:buscar }
    
mtd_empleados_idoneos:
    path:     /postulantes/idoneos/{id}
    defaults: {_controller: MTDReclutamientoBundle:BuscadorEmpleados:mostrarIdoneos }