mtd_sueldos_salarios:
    resource: "@MTDSueldosSalariosBundle/Resources/config/routing.yml"
    prefix:   /

mtd_asistencia:
    resource: "@MTDAsistenciaBundle/Resources/config/routing.yml"
    prefix:   /

mtd_seleccion:
    resource: "@MTDSeleccionBundle/Resources/config/routing.yml"
    prefix:   /

mtd_reclutamiento:
    resource: "@MTDReclutamientoBundle/Resources/config/routing.yml"
    prefix:   /

mtd_proyecto:
    resource: "@MTDProyectoBundle/Resources/config/routing.yml"
    prefix:   /

mtd_categorias_trabajo:
    resource: "@MTDCategoriasTrabajoBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
