mtd_productividad_homepage:
    path:     /hello/{name}
    defaults: { _controller: MTDProductividadBundle:Default:index }

mtd_productividad_empleados:
    path:     /productividad/empleados
    defaults: {_controller: MTDProductividadBundle:ListaEmpleados:listar }
    
mtd_productividad_sueldos:
    path:     /productividad/sueldos/{id}
    defaults: {_controller: MTDProductividadBundle:Sueldos:mostrar }
    
mtd_productividad_faltas:
    path:     /productividad/faltas/{id}
    defaults: {_controller: MTDProductividadBundle:Faltas:mostrar }
    
mtd_productividad_permisos:
    path:     /productividad/permisos/{id}
    defaults: {_controller: MTDProductividadBundle:Permisos:mostrar }
    
mtd_productividad_horas:
    path:     /productividad/horasTrabajadas/{id}
    defaults: {_controller: MTDProductividadBundle:Horas:mostrar }