mtd_sueldos_salarios_homepage:
    path:     /hello/{name}
    defaults: { _controller: MTDSueldosSalariosBundle:Default:index }

mtd_sueldos_ver:
    path:     /sueldosSalarios/ver
    defaults: {_controller: MTDSueldosSalariosBundle:MuestraSueldos:mostrar }
    
mtd_descuentos_empleados:
    path:     /descuentos/empleados
    defaults: {_controller: MTDSueldosSalariosBundle:DescuentosEmpleados:listar }
    
mtd_descuentos_registro:
    path:     /descuento/registro/{id}
    defaults: {_controller: MTDSueldosSalariosBundle:DescuentosEmpleados:mostrar }
    
mtd_registro_afps_anticipos:
    path:     /descuento/afpsAnticipo/{id}
    defaults: {_controller: MTDSueldosSalariosBundle:DescuentosEmpleados:registrar }
    
mtd_viaticos_registro:
    path:     /viaticos/registro/{id}
    defaults: {_controller: MTDSueldosSalariosBundle:ViaticosPremios:mostrar }
    
mtd_viaticos_premios_registro:
    path:     /viaticosPremios/registro/{id}
    defaults: {_controller: MTDSueldosSalariosBundle:ViaticosPremios:registrar }
    
mtd_sueldoDetalle_diasNoTrabajados:
    path:     /sueldo/detalle/diasNoTrabajados/{id}
    defaults: {_controller: MTDSueldosSalariosBundle:DetalleSueldos:diasNoTrabajados }
    options:
        expose: true
        
mtd_sueldoDetalle_horasExtras:
    path:     /sueldo/detalle/horasExtras/{id}
    defaults: {_controller: MTDSueldosSalariosBundle:DetalleSueldos:horasExtras }
    options:
        expose: true
        
mtd_sueldoDetalle_bonoAntiguedad:
    path:     /sueldo/detalle/bonoAntiguedad/{id}
    defaults: {_controller: MTDSueldosSalariosBundle:DetalleSueldos:bonoAntiguedad }
    options:
        expose: true
        
mtd_sueldoDetalle_descuentos:
    path:     /sueldo/detalle/descuentos/{id}
    defaults: {_controller: MTDSueldosSalariosBundle:DetalleSueldos:descuentos }
    options:
        expose: true
        
mtd_sueldoDetalle_premios:
    path:     /sueldo/detalle/premios/{id}
    defaults: {_controller: MTDSueldosSalariosBundle:DetalleSueldos:premios }
    options:
        expose: true