<?php

namespace MTD\CategoriasTrabajoBundle\Entity;

/**
 * Requisito_CategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Requisito_CategoriaRepository extends \Doctrine\ORM\EntityRepository
{
}
