<?php

namespace MTD\AsistenciaBundle\Entity;

/**
 * Asistencia_ProyectoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Asistencia_ProyectoRepository extends \Doctrine\ORM\EntityRepository
{
}
