<?php

namespace MTD\ProyectoBundle\Entity;

/**
 * ProyectoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProyectoRepository extends \Doctrine\ORM\EntityRepository
{
}
