<?php

namespace MTD\ProyectoBundle\Entity;

/**
 * Tipo_ProyectoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Tipo_ProyectoRepository extends \Doctrine\ORM\EntityRepository
{
}
