<?php

namespace MTD\SeleccionBundle\Entity;

/**
 * AscensoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AscensoRepository extends \Doctrine\ORM\EntityRepository
{
}
