<?php

namespace MTD\SeleccionBundle\Entity;

/**
 * ContratacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContratacionRepository extends \Doctrine\ORM\EntityRepository
{
}
