<?php

namespace MTD\SeleccionBundle\Entity;

/**
 * Proyecto_EmpleadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Proyecto_EmpleadoRepository extends \Doctrine\ORM\EntityRepository
{
}
